
// SDL2+opengl implementation of backend
#include "src/application.cpp"
#include "src/bitmapfont.cpp"
#include "src/bitmapfontcontent.cpp"
#include "src/draw.cpp"
#include "src/files.cpp"
#include "src/font.cpp"
#include "src/fontview.cpp"
#include "src/keyutils.cpp"
#include "src/paint.cpp"
#include "src/shaderobject.cpp"
#include "src/shaderprogram.cpp"
#include "src/standardshaderprogram.cpp"
#include "src/texture.cpp"
#include "src/translateshader.cpp"
#include "src/window.cpp"
